### PR TITLE
Add GCC diagnostics to suppress unused-parameter warnings

### PR DESCRIPTION
**Pull request by andresag01**
@rgrover @LiyouZhou

### CODE REVIEW

**Comment by rgrover** [comment]
+1

**Comment by rgrover** [comment]
it would be nice to add a mention of why this works.

**Comment by LiyouZhou** [comment]
@rgrover  We need to bump patch version and republish, do you want me to do that?

**Comment by rgrover** [comment]
I thought I had done this, let me check.

**Comment by andresag01** [comment]
I just built one of the demos and it seems that the change has not been published

**Comment by rgrover** [comment]
in that case, please publish an update

**Comment by LiyouZhou** [comment]
@rgrover @andresag01  new version published. v1.0.1

**Comment by andresag01** [comment]
Thanks, I can see the changes now.

**Comment by rgrover** [comment]
:+1:

**Pull request merged**
