### PR TITLE
Add ifdef to include correct mbed.h file in mbedOS

### PR DESCRIPTION
**Pull request by andresag01**
@LiyouZhou @pan- @rgrover

### CODE REVIEW

**Comment by rgrover** [comment]
this module is going to be used in mbedOS only. But perhaps it is not too bad to have a mbed-classic specific version of the include.

@pan-  please take over this PR.

**Comment by ghost** [comment]
ping?

**Comment by LiyouZhou** [comment]
I will revisit this after #13 goes through.

**Comment by pan-** [comment]
No need to revisit it, I merge it.

**Pull request merged**
