### PR TITLE
Nordic sdk 10.0.0

### PR DESCRIPTION
**Pull request by LiyouZhou**
Tests:

clitest - all expected passes pass, all expected fails fail.
build - all ble-examples build successfully
pstorage - tested eddystoneservice and works
dfu - tested to work
mbed-classic: compiles

The changes are minor. Mostly to do with getting ready for nrf52

@ARMmbed/ble-owners  Please review.

### CODE REVIEW

**Comment by ghost** [comment]
when 11.0 is released, do you plan on renaming the module to  nrf5-sdk ? it seems that's what they name the SDK now.

**Comment by LiyouZhou** [comment]
There is no plan yet for v11. But renaming this module will break dependencies, so we probably won't do that.

**Comment by ghost** [comment]
ah, yotta doesn't have a package X obsoletes package Y functionality yet then.

**Comment by andresag01** [comment]
+1, tried this by manually linking the module to the HeartRate ble-example and everything seems to work as expected.

**Comment by pan-** [comment]
Everything work perfectly on all examples and tests. 
I merge it.

**Pull request merged**
